BEGIN TRANSACTION;
CREATE TABLE planetData (planetID INTEGER PRIMARY KEY, planetName TEXT, planetDis REAL, planetScale REAL, planetPosX REAL, planetPosY REAL, planetPosZ REAL);
INSERT INTO planetData VALUES(1,'Sun',0.0,30.0,0.0,0.0,0.0);
INSERT INTO planetData VALUES(2,'Mercury',0.76,0.1,'','','');
INSERT INTO planetData VALUES(3,'Venus',1.42,0.26,NULL,NULL,NULL);
INSERT INTO planetData VALUES(4,'Earth',1.97,0.27,NULL,NULL,NULL);
INSERT INTO planetData VALUES(5,'Mars',3.0,0.15,NULL,NULL,NULL);
INSERT INTO planetData VALUES(6,'Jupiter',10.25,3.0,NULL,NULL,NULL);
INSERT INTO planetData VALUES(7,'Saturn',18.8,2.5,NULL,NULL,NULL);
INSERT INTO planetData VALUES(8,'Uranus',37.8,1.0,NULL,NULL,NULL);
INSERT INTO planetData VALUES(9,'Neptune',59.2,0.98,NULL,NULL,NULL);
INSERT INTO planetData VALUES(10,'Pluto',77.8,0.05,NULL,NULL,NULL);
CREATE TABLE stationData (stationName TEXT, stationPosX REAL, stationPosY REAL, stationPosZ REAL, stationScale REAL);
COMMIT;
